# Lecture 07: Mathematical operations in Python: NumPy

Instructor:
<br>**Md Shahidullah Kawsar**
<br>Data Scientist
<br>IDARE, Houston, TX, USA

#### Objectives:
1. Comparison between List and NumPy array
2. 1D and 2D NumPy array
3. Mathematical and Matrix operation in NumPy array
4. NumPy array slicing and filtering

#### References:
1. Mathematical functions in NumPy: https://numpy.org/doc/stable/reference/routines.math.html
2. Multiplying a matrix by a matrix: https://www.youtube.com/watch?v=OMA2Mwo0aZg&ab_channel=KhanAcademy

#### Comparison of List and NumPy array

In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4,5,6,7,8,9]
list_2 = [1,-2,3,-4,5,-6,7,-8,9]

list_add = list_1 + list_2
print(list_add)

# list_sub = list_1 - list_2
# print(list_sub)

# list_mul = list_1 * list_2
# print(list_mul)

# list_sub = list_1 / list_2
# print(list_sub)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, -2, 3, -4, 5, -6, 7, -8, 9]


In [3]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = np.array([1,-2,3,-4,5,-6,7,-8,9])

print(type(arr_1))
print(type(arr_2))
print(arr_2.dtype)

arr_add = arr_1 + arr_2
print("addition of two array = ", arr_add)
print(type(arr_add))

# arr_add = np.add(arr_3, arr_4)
# print(arr_add)

arr_sub = arr_1 - arr_2
print("subtraction of two array = ", arr_sub)

# arr_sub = np.subtract(arr_3, arr_4)
# print(arr_sub)

arr_mul = arr_1 * arr_2
print("multiplication of two array = ", arr_mul)

# arr_mul = np.multiply(arr_3, arr_4)
# print(arr_mul)

arr_div = arr_1 / arr_2
print("division of two array = ", arr_div)

# arr_div = np.divide(arr_5, arr_6)
# print(arr_div)

arr_mod = np.mod(arr_1, arr_2)
print("remainder after dividing two arrays = ", arr_mod)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
addition of two array =  [ 2  0  6  0 10  0 14  0 18]
<class 'numpy.ndarray'>
subtraction of two array =  [ 0  4  0  8  0 12  0 16  0]
multiplication of two array =  [  1  -4   9 -16  25 -36  49 -64  81]
division of two array =  [ 1. -1.  1. -1.  1. -1.  1. -1.  1.]
remainder after dividing two arrays =  [0 0 0 0 0 0 0 0 0]


In [4]:
arr_3 = np.array([[1,2,3], 
                  [4,5,6]])

arr_4 = np.array([[1,2,3], 
                  [4,5,6]])

print("array_3 = \n", arr_3)
print(type(arr_3))
print(arr_4.shape)
print("array_4 = \n", arr_4)

arr2d_add = arr_3 + arr_4
print("2d array addition = \n", arr2d_add)

arr2d_mul = arr_3 * arr_4
print("2d array multiplication = \n", arr2d_mul)

array_3 = 
 [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
array_4 = 
 [[1 2 3]
 [4 5 6]]
2d array addition = 
 [[ 2  4  6]
 [ 8 10 12]]
2d array multiplication = 
 [[ 1  4  9]
 [16 25 36]]


In [5]:
arr_5 = np.array([2, 2, 2, 2, 2])
arr_6 = np.array([1, 2, 3, 4, 5])
arr_7 = np.array([1.05, -2, 3.5, -4, 5.75])

arr_pow = np.power(arr_5, arr_6)
print(arr_pow)

arr_square = np.square(arr_6)
print(arr_square)

arr_abs = np.abs(arr_7)
print(arr_abs)

arr_ceil = np.ceil(arr_7)
print(arr_ceil)

arr_floor = np.floor(arr_7)
print(arr_floor)

arr_round = np.round(arr_7)
print(arr_round)

[ 2  4  8 16 32]
[ 1  4  9 16 25]
[1.05 2.   3.5  4.   5.75]
[ 2. -2.  4. -4.  6.]
[ 1. -2.  3. -4.  5.]
[ 1. -2.  4. -4.  6.]


#### array sum

In [6]:
arr_sum = np.sum([arr_5, arr_6])
print(arr_sum)

column_sum = np.sum([arr_5, arr_6], axis=0)
print(column_sum)

row_sum = np.sum([arr_5, arr_6], axis=1)
print(row_sum)

25
[3 4 5 6 7]
[10 15]


#### array product

In [7]:
arr_prod = np.prod([arr_5, arr_6])
print(arr_prod)

column_prod = np.prod([arr_5, arr_6], axis=0)
print(column_prod)

row_prod = np.prod([arr_5, arr_6], axis=1)
print(row_prod)

3840
[ 2  4  6  8 10]
[ 32 120]


#### Matrix operation

In [8]:
arr_8 = np.array([[1,0,0], 
                  [0,1,0],
                  [0,0,1]])

arr_9 = np.array([[1,2,3], 
                  [4,5,6],
                  [7,8,9]])

arr_matmul = np.matmul(arr_8, arr_9)
print(arr_matmul)

arr_diag = np.diag(arr_9)
print(arr_diag)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


#### Creating new matrix

In [9]:
identity_matrix = np.eye(3)
print(identity_matrix)

identity_ones = np.ones((3,3))
print(identity_ones)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Array indexing and slicing

In [10]:
# print(arr_3[0])
# print(arr_3[1])
# print(arr_3[0,0])
# print(arr_3[0,1])
# print(arr_3[0,2])
# print(arr_3[1,0])
# print(arr_3[1,1])
# print(arr_3[1,2])

# print(arr_3[0,-1])
# print(arr_3[0,-2])
# print(arr_3[0,-3])

print(arr_3[:,0:1])
# print(arr_3[1:])

[[1]
 [4]]


#### numpy array filtering

In [11]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

find_four = np.where(arr == 4)
find_even = np.where(arr%2 == 0)
find_odd = np.where(arr%2 == 1)

print("index of value 4 : ", find_four)
print("index of the even numbers in the array : ", find_even)
print("index of the odd numbers in the array : ", find_odd)


index of value 4 :  (array([3, 5, 6]),)
index of the even numbers in the array :  (array([1, 3, 5, 6]),)
index of the odd numbers in the array :  (array([0, 2, 4]),)


In [12]:
find = arr[arr >= 4]

print(arr >= 4)
print(find)

[False False False  True  True  True  True]
[4 5 4 4]
